### ISSUE TITLE
Delay introduced when reading sensor from v1.2.0 to v2.0.1

### ISSUE THREAD

**Issue by TheScepticalRabbit** [adafruit/Adafruit_VEML7700#16]
- Arduino board:  Adafruit Metro M4

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.16

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): 
I am using two adafruit VEML7700 breakouts through an adafruit TCA9548A mulitplexer to track light as a function on my robot. I updated to the latest version of the library v2.0.1 and this caused massive delays in my main loop (on the order of 800ms). Reverting back to version v1.2.0 the delays disappeared and the code functioned normally. I went into the header and cpp and compared them for the new and old library and a new function has been introduced readWait() which calls 'delay()' every time the readlux() function is called. I would suggest removing the use of delay() as it does not allow the user to manage their own timing and essentially bricks the main board when 'readlux()' is called. The previous version of the sensor code allowed the main control loop of my robot to manage other tasks while waiting for the integration time of the light sensor (e.g. running the PIDs controlling the motor speed).

**Comment by caternuson** [comment]
Yep, this is essentially known, see comment here:
https://github.com/adafruit/Adafruit_VEML7700/pull/15#issuecomment-1137881797

We can update things, but thought best to wait for a good use case to base things on. Seems like you have one :)

Can you provide more details about how you were managing tracking integration time in your setup. Did it matter if you got the same reading back to back by attempting to read the sensor too fast? Were you adjusting your reading rate based on integration time?

Also - may not apply to your use case, but I don't think there's an easy way to do this for the new "auto" lux feature added, since that needs to loop on several reads of the sensor and iterate as needed. And the reads should be "good" - so must ensure waiting the appropriate time.

**Comment by TheScepticalRabbit** [comment]
Thanks for the info. Sure, happy to provide more details on my setup. 

RE "Managing tracking integration time" - I just use a fixed integration time for the sensor and use my own timer class combined with an if statement to work out when to call the sensor for a new reading. I just made sure that my own timer had an interval equal to or greater than the integration time.

RE "Did it matter if you got the same reading back to back by attempting to read the sensor too fast?" - No this does not matter, it just means that the robot will respond in the same way for the next read interval which is short compared to the speed at which the robot is moving. In the following read interval the sensors will update again and the robot will correct.

RE "Were you adjusting your reading rate based on integration time?" - Yes, I was using a fixed integration time so I could just set the timing interval in my timer class to sync with the sensor.

RE "new "auto" lux feature" - I don't think I will be using this in my application. A fixed integration time and gain seems to work well for getting the robot to chase the flash light on my mobile phone :).

**Comment by caternuson** [comment]
Cool. Thanks for all the additional information. Seems like this can be done fairly simply. Submitted a PR here if you want to try testing: #17 

Note that you'll likely still need to make some minor modifications to your code. The `readALS()` function now returns the raw register value as an int. Should only be minor changes though, to adjust for the new value.

**Comment by caternuson** [comment]
Please try updating to the 2.1.0 release of the library when it becomes available via Library Manger:
https://github.com/adafruit/Adafruit_VEML7700/releases/tag/2.1.0

You may still need to make some minor changes to your code. Both `readALS()` and `readWhite()` will now read without any delays by default. So the delay behavior should be the same as before. However, the return value of `readALS()` was also changed with the 2.0.0 release. It now returns the raw int value from the register. Should only be minor changes needed to code to adjust for the new range in values.

If you want to use `readLux()` without delay, use one of the `NOWAIT` parameter options. Otherwise it will block by default.

**Comment by TheScepticalRabbit** [comment]
Just downloaded the new 2.1.0 release and updated the readLux() function to use the NOWAIT and my robot is now happily chasing my phone flashlight again. Thanks!
